let products = [
  {
    id: 1,
    category: "Bakery",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    card: 44.5,
    cash: 50.5,
    rating: 2,
    discount: "-50%",
    images: ["../assets/images/home/main/stock/cards/1.png"],
  },
  {
    id: 2,
    category: "Milky",
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
    card: 44.5,
    cash: 50.5,
    rating: 3,
    discount: "-50%",
    images: ["../assets/images/home/main/stock/cards/2.png"],
  },
  {
    id: 3,
    category: "Bakery",
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    card: 44.5,
    cash: 50.5,
    rating: 5,
    discount: "-50%",
    images: ["../assets/images/home/main/stock/cards/3.png"],
  },
  {
    id: 4,
    category: "Vegetable",
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    card: 44.5,
    cash: 50.5,
    rating: 4.5,
    discount: "-50%",
    images: ["../assets/images/home/main/stock/cards/4.png  "],
  },
  {
    id: 5,
    category: "Vegetable",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    card: " ",
    cash: 599.99,
    rating: 2,
    discount: "0",
    images: ["../assets/images/home/main/new__goods/cards/1.png"],
  },
  {
    id: 6,
    category: "Dairy",
    description:
      "A dairy product made from milk, with a variety of textures and flavors.",
    card: 91,
    cash: 91,
    rating: 3.5,
    discount: 50,
    images: ["../assets/images/home/main/new__goods/cards/2.png"],
  },
  {
    id: 7,
    category: "Meat",
    description:
      "A type of poultry, often used as a source of protein in meals.",
    card: 68,
    cash: 68,
    rating: 3.5,
    discount: 20,
    images: ["../assets/images/home/main/new__goods/cards/3.png"],
  },
  {
    id: 8,
    category: "Dessert",
    description:
      "A sweet food made from cacao beans, used in a variety of desserts and confections.",
    card: 61,
    cash: 61,
    rating: 4.5,
    discount: 20,
    images: ["../assets/images/home/main/new__goods/cards/4.png"],
  },
  {
    id: 9,
    category: "Dessert",
    description:
      "A dark, bitter beverage made from roasted coffee beans, typically used as a pick-me-up.",
    card: 98,
    cash: 98,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/9.png",
      "../assets/images/products/10.png",
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
    ],
  },
  {
    id: 10,
    category: "Dairy",
    description:
      "A oval-shaped reproductive body produced by birds, often used as a source of protein in meals.",
    card: 79,
    cash: 79,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/10.png",
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
    ],
  },
  {
    id: 11,
    category: "Meat",
    description:
      "A type of seafood, known for its omega-3 fatty acids and high protein content.",
    card: 89,
    cash: 89,
    rating: 3.5,
    discount: 50,
    images: [
      "../assets/images/products/11.png",
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
    ],
  },
  {
    id: 12,
    category: "Fruit",
    description:
      "A small, sweet fruit that grows in clusters, often used in wine-making.",
    card: 61,
    cash: 61,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/12.png",
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
      "../assets/images/products/15.png",
    ],
  },
  {
    id: 13,
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    card: 87,
    cash: 87,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/13.png",
      "../assets/images/products/14.png",
      "../assets/images/products/15.png",
      "../assets/images/products/16.png",
    ],
  },
  {
    id: 14,
    category: "Fast food",
    description:
      "A type of sausage served in a long roll, often used as a quick and convenient food.",
    card: 84,
    cash: 84,
    rating: 4.5,
    discount: 50,
    images: [
      "../assets/images/products/14.png",
      "../assets/images/products/15.png",
      "../assets/images/products/16.png",
      "../assets/images/products/17.png",
    ],
  },
  {
    id: 15,
    category: "Dessert",
    description:
      "A frozen dessert made from cream, sugar, and flavorings, available in a variety of flavors.",
    card: 68,
    cash: 68,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/15.png",
      "../assets/images/products/16.png",
      "../assets/images/products/17.png",
      "../assets/images/products/18.png",
    ],
  },
  {
    id: 16,
    category: "Fruit",
    description:
      "A yellow citrus fruit with a tart, acidic flavor, often used in cooking and baking.",
    card: 74,
    cash: 74,
    rating: 3.5,
    discount: 0,
    images: [
      "../assets/images/products/16.png",
      "../assets/images/products/17.png",
      "../assets/images/products/18.png",
      "../assets/images/products/19.png",
    ],
  },
  {
    id: 17,
    category: "Dairy",
    description:
      "Eggs are oval-shaped reproductive structures produced by female birds and some reptiles.",
    card: 70,
    cash: 70,
    rating: 4.5,
    discount: 50,
    images: [
      "../assets/images/products/17.png",
      "../assets/images/products/18.png",
      "../assets/images/products/19.png",
      "../assets/images/products/20.png",
    ],
  },
  {
    id: 18,
    category: "Dairy",
    description:
      "Honey is a sweet, sticky liquid made by bees from the nectar of flowers.",
    card: 87,
    cash: 87,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/18.png",
      "../assets/images/products/19.png",
      "../assets/images/products/20.png",
      "../assets/images/products/21.png",
    ],
  },
  {
    id: 19,
    category: "Dessert",
    description:
      "Ice cream is a frozen dessert made from cream, sugar, and flavorings.",
    card: 83,
    cash: 83,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/19.png",
      "../assets/images/products/20.png",
      "../assets/images/products/21.png",
      "../assets/images/products/22.png",
    ],
  },
  {
    id: 20,
    category: "Fruit",
    description:
      "Jelly is a sweet spread made from fruit juice and sugar, often used as a topping for toast or pastries.",
    card: 76,
    cash: 76,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/20.png",
      "../assets/images/products/21.png",
      "../assets/images/products/22.png",
      "../assets/images/products/23.png",
    ],
  },
  {
    id: 21,
    category: "Dairy",
    description:
      "Ketchup is a tangy sauce made from tomatoes, vinegar, sugar, and spices.",
    card: 77,
    cash: 77,
    rating: 5,
    discount: 0,
    images: [
      "../assets/images/products/21.png",
      "../assets/images/products/22.png",
      "../assets/images/products/23.png",
      "../assets/images/products/24.png",
    ],
  },
  {
    id: 22,
    category: "Fruit",
    description:
      "Mangoes are juicy, sweet tropical fruits with a fleshy interior and a large, oblong seed in the center.",
    card: 80,
    cash: 80,
    rating: 5,
    discount: 20,
    images: [
      "../assets/images/products/22.png",
      "../assets/images/products/23.png",
      "../assets/images/products/24.png",
      "../assets/images/products/25.png",
    ],
  },
  {
    id: 23,
    category: "Meat",
    description:
      "Noodles are a type of pasta made from wheat flour and water, often used in Asian cuisine.",
    card: 93,
    cash: 93,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/23.png",
      "../assets/images/products/24.png",
      "../assets/images/products/25.png",
      "../assets/images/products/26.png",
    ],
  },
  {
    id: 24,
    category: "Breakfast",
    description:
      "Oatmeal is a type of porridge made from oats that is often served for breakfast.",
    card: 94,
    cash: 94,
    rating: 4.5,
    discount: 0,
    images: [
      "../assets/images/products/24.png",
      "../assets/images/products/25.png",
      "../assets/images/products/26.png",
      "../assets/images/products/27.png",
    ],
  },
  {
    id: 25,
    category: "Breakfast",
    description:
      "Bacon is a popular breakfast food made from cured pork belly, it is newly delivered.",
    card: 71,
    cash: 71,
    rating: 3.5,
    discount: 20,
    images: [
      "../assets/images/products/25.png",
      "../assets/images/products/26.png",
      "../assets/images/products/27.png",
      "../assets/images/products/28.png",
    ],
  },
  {
    id: 26,
    category: "Breakfast",
    description:
      "Pancakes are a popular breakfast food made from flour, eggs, and milk.",
    card: 63,
    cash: 63,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/26.png",
      "../assets/images/products/27.png",
      "../assets/images/products/28.png",
      "../assets/images/products/29.png",
    ],
  },
  {
    id: 27,
    category: "Breakfast",
    description:
      "Waffles are a type of breakfast food made from batter cooked in a waffle iron.",
    card: 97,
    cash: 97,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/27.png",
      "../assets/images/products/28.png",
      "../assets/images/products/29.png",
      "../assets/images/products/30.png",
    ],
  },
  {
    id: 28,
    category: "Lunch",
    description:
      "Fried Rice is a type of rice dish that is stir-fried in a pan with oil and other ingredients.",
    card: 81,
    cash: 81,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/28.png",
      "../assets/images/products/29.png",
      "../assets/images/products/30.png",
      "../assets/images/products/31.png",
    ],
  },
  {
    id: 29,
    category: "Lunch",
    description:
      "Spaghetti is a type of pasta made from wheat flour and water, usually served with sauce.",
    card: 96,
    cash: 96,
    rating: 3,
    discount: 50,
    images: [
      "../assets/images/products/29.png",
      "../assets/images/products/30.png",
      "../assets/images/products/31.png",
      "../assets/images/products/32.png",
    ],
  },
  {
    id: 30,
    category: "Lunch",
    description:
      "Pizza is a popular dish made from dough, sauce, cheese, and toppings.",
    card: 95,
    cash: 95,
    rating: 4,
    discount: 0,
    images: [
      "../assets/images/products/30.png",
      "../assets/images/products/31.png",
      "../assets/images/products/32.png",
      "../assets/images/products/33.png",
    ],
  },
  {
    id: 31,
    category: "Lunch",
    description:
      "A grilled cheese sandwich is a hot sandwich made from cheese and bread.",
    card: 100,
    cash: 100,
    rating: 5,
    discount: 50,
    images: [
      "../assets/images/products/31.png",
      "../assets/images/products/32.png",
      "../assets/images/products/33.png",
      "../assets/images/products/34.png",
    ],
  },
  {
    id: 32,
    category: "Dinner",
    description:
      "Steak is a popular dinner dish made from a cut of beef that is usually grilled or pan-fried.",
    card: 63,
    cash: 63,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/32.png",
      "../assets/images/products/33.png",
      "../assets/images/products/34.png",
      "../assets/images/products/35.png",
    ],
  },
  {
    id: 33,
    category: "Dinner",
    description:
      "Salmon is a type of fish that is often grilled or baked and served as a main course.",
    card: 82,
    cash: 82,
    rating: 4.5,
    discount: 20,
    images: [
      "../assets/images/products/33.png",
      "../assets/images/products/34.png",
      "../assets/images/products/35.png",
      "../assets/images/products/36.png",
    ],
  },
  {
    id: 34,
    category: "Dinner",
    description:
      "Chicken Alfredo is a pasta dish made with chicken, alsjfkdlkasdfhlkjh.",
    card: 94,
    cash: 94,
    rating: 4,
    discount: 20,
    images: [
      "../assets/images/products/34.png",
      "../assets/images/products/35.png",
      "../assets/images/products/36.png",
      "../assets/images/products/1.png",
    ],
  },
  {
    id: 35,
    category: "Dinner",
    description:
      "Lasagna is a type of pasta dish made with layers of pasta, sauce, cheese, and meat or vegetables.",
    card: 70,
    cash: 70,
    rating: 1,
    discount: 0,
    images: [
      "../assets/images/products/35.png",
      "../assets/images/products/36.png",
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
    ],
  },
  {
    id: 36,
    category: "Dessert",
    description:
      "Chocolate Chip Cookies are a type of cookie made from flour, sugar, butter, and chocolate chips.",
    card: 98,
    cash: 98,
    rating: 3.5,
    discount: 0,
    images: [
      "../assets/images/products/36.png",
      "../assets/images/products/1.png",
      "../assets/images/products/2.png",
      "../assets/images/products/3.png",
    ],
  },
];

// console.log(products);

export default products;
